Prepare for beta version
cheeseformice/cheese.formice.com pull request #1
Opened 2021-05-17 01:07 UTC by Tocutoeltuco

2021-05-17 01:28 UTC, SuspiciousLookingOwl requested changes

2021-05-17 01:28 UTC, SuspiciousLookingOwl commented on src/pages/Player/Profile.vue
> +          <span>«{{ title }}»</span>
this can be changed to
```html
<div>«{{ title }}»</div>
```

2021-05-17 01:28 UTC, SuspiciousLookingOwl commented on src/store/modules/Player.ts
> +  title: string | null = null;
Use empty string `""` for default value so the typing can be changed to just `string` instead of `string | null`

2021-05-17 01:28 UTC, SuspiciousLookingOwl commented on src/api/translations/service.ts
> +        return await axios.get(`${BASE}/${opt.language || "en"}`, { params: params });
This can be simplified to:

```js
    const params = {
      field: opt.fields,
      start: opt.start,
      all: opt.all,
    };

    return await axios.get(`${BASE}/${opt.language || "en"}`, {
      params,
      paramsSerializer: (p) => qs.stringify(p, { arrayFormat: "repeat" }),
    });
```

The `paramsSerializer` can be moved to `axios` declaration to avoid adding `paramsSerializer` every time we want to pass array as params, since the endpoint accept same arrayFormat anyway

On here: https://github.com/cheeseformice/cheese.formice.com/blob/beta/src/api/axios.ts#L8
```ts
axios.create({
    baseURL: API_BASE_URL,
    paramsSerializer: (p) => qs.stringify(p, { arrayFormat: "repeat" }),
})
  ```

2021-05-17 01:28 UTC, SuspiciousLookingOwl commented on src/api/translations/interfaces.ts
> +}
This type can be changed to
```ts
export type TranslationFields = Record<string, string>;
```

2021-05-18 01:52 UTC, SuspiciousLookingOwl commented on src/api/players/service.ts
> +
Should we change the parameter name to `last` to make it consistent? This also allows you to do shorthand property name:

```js
static async getLastSeen(last: number): Promise<AxiosResponse<BasePlayer[]>> {
    return await axios.get(BASE, { params: { last }});
}
```

2021-05-18 01:52 UTC, SuspiciousLookingOwl commented on src/api/tribes/service.ts
> +
Should we change the parameter name to `last` to make it consistent? This also allows you to do shorthand property name:

```js
static async getLastSeen(last: number): Promise<AxiosResponse<BasePlayer[]>> {
    return await axios.get(BASE, { params: { last }});
}
```

2021-05-18 01:54 UTC, SuspiciousLookingOwl commented on src/pages/Index.vue
> +    <div class="row q-col-gutter-md">
Instead of adding `class="q-mt-lg"` to each table, I think putting the `q-mt-lg` class here instead will lead to similar result

2021-05-18 15:32 UTC, Tocutoeltuco commented on src/pages/Index.vue
> +    <div class="row q-col-gutter-md">
Removing q-mt-lg doesn't have a big effect, and kind of looks better. I'll just remove it.

2021-05-20 03:51 UTC, SuspiciousLookingOwl requested changes

2021-05-20 03:51 UTC, SuspiciousLookingOwl commented on src/pages/Tribe/Members.vue
> +        />
`:max` value supposed to be `Math.ceil(total / itemsPerPage)`

```html
 <q-pagination
      v-model="lookup.page"
      outline
      :max-pages="7"
      :max="Math.ceil(total / itemsPerPage)"
/>
```

you can also create computed value on the script tag like this:

```js
get totalPages() {
    return Math.ceil(this.total / this.itemsPerPage);
}
```
then use it in the template like this:
```html
 <q-pagination
      v-model="lookup.page"
      outline
      :max-pages="7"
      :max="totalPages"
/>
```

---

Also `:boundary-numbers="false"` can be removed so users can skip to last / first page (since we already have page count)

2021-05-20 03:51 UTC, SuspiciousLookingOwl commented on src/pages/Tribe/Members.vue
> +        />
Apply same changes as above

2021-05-20 03:51 UTC, SuspiciousLookingOwl commented on src/pages/Tribe/Members.vue
> +      this.lookup.period ? this.lookup.period.value : "",
This can be simplified to:
```js
this.lookup.sort?.value  || "",   
this.lookup.period?.value || "",
```

2021-05-20 04:04 UTC, SuspiciousLookingOwl requested changes

2021-05-20 04:04 UTC, SuspiciousLookingOwl commented on src/pages/Tribe/Members.vue
> +    return options;
This can be simplified to:
```js
    return [
      {
        label: this.$t("sorts.none"),
        value: "",
      },
      ...sortNames.map((n) => ({
        label: this.$t(`sorts.${n}`),
        value: n
      })),
    ];
```

2021-05-20 04:04 UTC, SuspiciousLookingOwl commented on src/pages/Tribe/Members.vue
> +      "overall",
Should we put `overall` on the top? Since it's probably the most common leaderboard that users want to see

2021-05-20 04:04 UTC, SuspiciousLookingOwl commented on src/pages/Tribe/Members.vue
> +  searchCheckInterval?: any;
`searchCheckInterval` type can be changed to `number` so we can avoid the ugly eslint ignore comment

2021-05-20 04:04 UTC, SuspiciousLookingOwl commented on src/pages/Tribe/Members.vue
> +    this.searchCheckInterval = setInterval(() => {
If you change `searchCheckInterval` type to `number`, you can use `window.setInterval` instead of `setInterval`

2021-05-20 04:06 UTC, Tocutoeltuco commented on src/pages/Tribe/Members.vue
> +    this.searchCheckInterval = setInterval(() => {
setInterval returned Timeout type instead of number, and I didnt know where to import it from so I kept any

If window.setInterval returns a number, that's gonna be better

2021-05-20 04:11 UTC, SuspiciousLookingOwl commented on src/pages/Tribe/Members.vue
> +    this.searchCheckInterval = setInterval(() => {
It's supposed to be `NodeJS.Timeout` but TypeScript might complain that `NodeJS` is undefined, so yeah just use `window.setInterval`

2021-05-24 00:04 UTC, merged